const fs = require('fs');
const path = require('path');

// ── Helpers ──────────────────────────────────────────
function readDir(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).filter(f => f.endsWith('.md'));
}

function getWeekNumber() {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 1);
  return Math.ceil(((now - start) / 86400000 + start.getDay() + 1) / 7);
}

// ── Count metrics ─────────────────────────────────────
const sentenceFiles = readDir('writing/sentences');
const task1Files    = readDir('writing/task1');
const task2Files    = readDir('writing/task2');
const bugLogPath    = 'bug-log/grammar-bugs.md';
const weeklyFiles   = readDir('weekly-review').filter(f => f.startsWith('week-'));

// Count bug entries
let bugCount = 0;
if (fs.existsSync(bugLogPath)) {
  const bugContent = fs.readFileSync(bugLogPath, 'utf8');
  bugCount = (bugContent.match(/^## Bug ID/gm) || []).length;
}

// Count total sentences written
let totalSentences = 0;
sentenceFiles.forEach(file => {
  const content = fs.readFileSync(path.join('writing/sentences', file), 'utf8');
  const matches = content.match(/^\d+\./gm) || [];
  totalSentences += matches.length;
});

// Find most common bug category
let topBug = 'N/A';
if (fs.existsSync(bugLogPath)) {
  const bugContent = fs.readFileSync(bugLogPath, 'utf8');
  const categories = bugContent.match(/^Category: .+/gm) || [];
  const freq = {};
  categories.forEach(c => {
    const cat = c.replace('Category: ', '').trim();
    freq[cat] = (freq[cat] || 0) + 1;
  });
  topBug = Object.entries(freq).sort((a, b) => b[1] - a[1])[0]?.[0] || 'N/A';
}

const weekNum = getWeekNumber();
const dateStr = new Date().toISOString().split('T')[0];

// ── Generate weekly report ────────────────────────────
const report = `# Auto Weekly Learning Report — Week ${weekNum}

Generated: ${dateStr}

## 📊 Metrics This Week

| Metric | Value |
|---|---|
| Sentence practice files | ${sentenceFiles.length} |
| Task 1 essays | ${task1Files.length} |
| Task 2 essays | ${task2Files.length} |
| Total sentences written | ~${totalSentences} |
| Grammar bugs logged | ${bugCount} |
| Most common bug category | ${topBug} |
| Weekly review files | ${weeklyFiles.length} |

## 🎯 Next Steps

- Review Bug ID entries in \`bug-log/grammar-bugs.md\`
- Focus on fixing: **${topBug}**
- Target next week: add 50+ new sentences

---
*Auto-generated by scripts/generate_report.js via GitHub Actions*
`;

const outPath = `weekly-review/auto-report-week-${String(weekNum).padStart(2,'0')}.md`;
fs.writeFileSync(outPath, report);
console.log(`✅ Report generated: ${outPath}`);

// ── Update progress dashboard ─────────────────────────
const dashboard = `# English Learning Dashboard

Last updated: ${dateStr}

## 📈 Overall Progress

| Metric | Value |
|---|---|
| Sentence files | ${sentenceFiles.length} |
| Task 1 essays | ${task1Files.length} |
| Task 2 essays | ${task2Files.length} |
| Grammar bugs logged | ${bugCount} |
| Most persistent bug | ${topBug} |

## 🏁 Targets

- [ ] 60 commits
- [ ] 20+ essays
- [ ] 100+ grammar bugs fixed
- [ ] 800–1000 vocabulary
- [ ] Score 70+/100 on final test
`;

fs.writeFileSync('progress-dashboard.md', dashboard);
console.log('✅ Dashboard updated: progress-dashboard.md');
